# Generated by Django 5.2.4 on 2025-07-31 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='faresession',
            old_name='last_tap_at',
            new_name='tap_in_time',
        ),
        migrations.RemoveField(
            model_name='faresession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='faresession',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='faresession',
            name='user',
        ),
        migrations.AddField(
            model_name='faresession',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='faresession',
            name='tap_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faresession',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fare.passenger'),
            preserve_default=False,
        ),
    ]
