# Generated by Django 5.2.4 on 2025-08-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0002_passenger_rename_last_tap_at_faresession_tap_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fare_zone', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tapevent',
            name='location',
        ),
        migrations.AddField(
            model_name='tapevent',
            name='stage',
            field=models.CharField(default='Kampala', max_length=100),
        ),
        migrations.AddField(
            model_name='faresession',
            name='entry_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sessions', to='fare.stage'),
        ),
        migrations.AddField(
            model_name='faresession',
            name='exit_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_sessions', to='fare.stage'),
        ),
    ]
