# Generated by Django 5.2.4 on 2025-08-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fare', '0003_stage_remove_tapevent_location_tapevent_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_charged',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
